name: Build with CMake (Linux)

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      CLANG_VERSION: 18
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt upgrade && sudo apt install -y libunwind-dev apt-transport-https \
          ca-certificates curl wget gnupg make cmake lsb-release software-properties-common \
          libeigen3-dev libkdl-parser-dev libgflags-dev libgoogle-glog-dev liborocos-kdl-dev \
          libgtest-dev libyaml-cpp-dev liburdf-dev python3-pip libfcl-dev libnanoflann-dev \
          && pip3 install trimesh urdfpy && \
          wget https://apt.llvm.org/llvm.sh && \
          sed -i "s/add-apt-repository \"${REPO_NAME}\"/add-apt-repository \"${REPO_NAME}\" -y/g" llvm.sh && \
          chmod +x llvm.sh && \
          ./llvm.sh $CLANG_VERSION -y && \
          apt-get install -y --no-install-recommends clang-$CLANG_VERSION clang-tidy-$CLANG_VERSION clang-format-$CLANG_VERSION \
          llvm-$CLANG_VERSION-dev libc++-$CLANG_VERSION-dev libomp-$CLANG_VERSION-dev libc++abi-$CLANG_VERSION-dev libunwind-$CLANG_VERSION-dev && \
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-$CLANG_VERSION $CLANG_VERSION \
          --slave /usr/bin/clang++ clang++ /usr/bin/clang++-$CLANG_VERSION \
          --slave /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-$CLANG_VERSION \
          --slave /usr/bin/clang-format clang-format /usr/bin/clang-format-$CLANG_VERSION
        shell: bash

      - name: Configure with CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          mkdir -p build
          cmake --build build --config Release

      - name: Test (optional)
        run: |
          if [ -d build/tests ]; then
            ctest --test-dir build/tests -C Release --output-on-failure
          fi
